# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/github-monitor

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
      - run:
          name: install dependencies
          command: pipenv install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-
      - run:
          name: run tests
          command: |
            pipenv run coverage run --source='.' manage.py test
            coverage report
            npm run test
      - store_artifacts:
          path: test-reports
          destination: test-reports
