# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: docker pull nikolaik/python-nodejs

    working_directory: ~/github-monitor

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            pipenv install
            pipenv install --dev

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-
      - run:
          name: run tests
          command: |
            - npm run build
            - npm run lint
            # style check
            - pipenv run prospector
            # security checks
            - pipenv run bandit -r .
            - pipenv check
            # imports check
            - pipenv run isort **/*.py --check-only
            # pre-commit additional checks
            - SKIP=prospector,isort,eslint,missing-migrations pipenv run pre-commit run --all-files
            - >-
              DJANGO_SETTINGS_MODULE=github_monitor.settings.local_base
              pipenv run python manage.py has_missing_migrations --ignore authtools;
            - >-
              DJANGO_SETTINGS_MODULE=github_monitor.settings.production
              SECRET_KEY=$(python -c 'import uuid; print(uuid.uuid4().hex + uuid.uuid4().hex)')
              DATABASE_URL='sqlite:///'
              ALLOWED_HOSTS='.example.org'
              REDIS_URL='redis://'
              pipenv run python manage.py check --deploy
            - pipenv run coverage run manage.py test
            - npm run test
            - pipenv run coverage report
      - store_artifacts:
          path: test-reports
          destination: test-reports
