# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 18:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='users',
            field=models.ManyToManyField(related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='monitor.Repository', verbose_name='repository'),
        ),
    ]
