# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20180404_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='monitor.Repository'),
        ),
    ]
