# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0002_auto_20180403_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='created_by',
        ),
        migrations.AddField(
            model_name='repository',
            name='users',
            field=models.ManyToManyField(related_name='repositories', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
