# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20180405_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='hook',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
