# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180403_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
