# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_repository_hook'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
