# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20180403_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='monitor.Repository', verbose_name='repository'),
        ),
    ]
