# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_commit_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ('-date',), 'verbose_name': 'Commit', 'verbose_name_plural': 'Commits'},
        ),
    ]
