# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20180407_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
