# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_commit_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='branch',
            field=models.CharField(default='master', max_length=255),
            preserve_default=False,
        ),
    ]
